### ISSUE TITLE
Consider making frappe-charts a peer dependency

### ISSUE THREAD

**Issue by kripod** [sheshbabu/react-frappe-charts#10]
As a library which strongly depends on Frappe, I would suggest specifying `frappe-charts` as a peer dependency to let developers have finer control over its version.

**Comment by sheshbabu** [comment]
@kripod  I've released a new version 3.0.0 that moves the `frappe-charts` dependency to `peerDependencies` 👍

**Comment by kripod** [comment]
Wonderful, thank you! 😊
