### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module when running tests.

### ISSUE THREAD

**Issue by drzamich** [sheshbabu/react-frappe-charts#12]
Hi. I imported `react-frappe-charts` in my app created with Create React App. It works fine but when I try to run any unit tests I  get an error
```
  ● Test suite failed to run

    /node_modules/react-frappe-charts/build/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import React from "react";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
I  believe this is because the library is using ES6 modules in production. Would you consider transpiling the code before publishing to npm?

Meanwhile, Can anyone think of a workaround so that I can run my tests?

**Comment by sheshbabu** [comment]
Hi @drzamich, you can try transpiling this module when running test. Can you try this suggestion - https://github.com/facebook/jest/issues/6229#issuecomment-403539460

**Comment by sheshbabu** [comment]
Closed due to inactivity. @drzamich Please feel free to reopen if you're still facing this issue 🙂

**Comment by aquiab** [comment]
got around it by setting my jest config with 
`"transformIgnorePatterns": ["/node_modules/(?!(react-frappe-charts|frappe-charts)/)"]`
and changing .babelrc to babel.config.js and module exporting it
