### ISSUE TITLE
How to export chart in react-frappe-charts ?

### ISSUE THREAD

**Issue by CristianWesleyFront** [sheshbabu/react-frappe-charts#7]
I don't find export function in react-frappe-charts. 
![image](https://user-images.githubusercontent.com/26757758/75676333-c8e41880-5c67-11ea-9c0b-f2dbaab9bb9a.png)

**Comment by sheshbabu** [comment]
This feature has been added - https://github.com/sheshbabu/react-frappe-charts#export-chart
